apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: jermuk-city-runner-deploy
  namespace: arc
spec:
  replicas: 1
  template:
    spec:
      repository: Blackdocs-Cloud/jermuk-city